version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: .
          paths:
            - models
            - test-results

  deploy:
    docker:
      - image: python:3.8

    steps:
      - attach_workspace:
          at: /workspace

      # Install Streamlit
      - run:
          name: Install Streamlit
          command: |
            pip install streamlit

      # Deploy Streamlit app
      - run:
          name: Deploy Streamlit App
          command: |
            streamlit run app.py &

  download_artifacts:
    docker:
      - image: cibuilds/hello-docker

    steps:
      - attach_workspace:
          at: /workspace

      - run:
          name: Download Artifacts
          command: |
            mkdir -p $HOME/artifacts
            cp -R /workspace/test-results $HOME/artifacts
            ls -la $HOME/artifacts


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master

     - download_artifacts:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
