version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
      - store_test_results:
          path: /tmp/test-results
  deploy:
    docker:
      - image: lambdatest/python-node
    steps:
      - checkout
      - run:
          name: Deploy to LambdaTest
          command: ./deploy.sh
  save_artifacts:
    docker:
      - image: python:3.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Save artifacts
          command: cp -r /tmp/workspace/* /tmp/artifacts
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
      - save_artifacts:
          requires:
            - deploy
