version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            #pip install -r requirements.txt
            #python3 -m venv venv
            #source venv/bin/activate
            #pip install --no-cache-dir --disable-pip-version-check --no-build-isolation -r requirements.txt
            pip install -r requirements.txt

      # Install npm
      - run:
          name: Install npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
            apt-get install -y nodejs

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            #source venv/bin/activate
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      # Save plots as artifacts
      - persist_to_workspace:
          root: .
          paths:
            - scatter_plot.html
            - pie_plot.html
            - bar_plot.html
            - line_plot.html

  deploy:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      # Build Docker image
      - run:
          name: Build and push to Docker Hub
          command: |
            # Install Firebase CLI
            npm install -g firebase-tools

            # Authenticate with Firebase (replace FIREBASE_TOKEN with your Firebase token)
            firebase login:ci --token "$FIREBASE_TOKEN"

            # Deploy to Firebase hosting
            firebase deploy --only hosting

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
