version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      # Save plots as artifacts
      - persist_to_workspace:
          root: .
          paths:
            - scatter_plot.html
            - pie_plot.html
            - bar_plot.html
            - line_plot.html

  deploy:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      # Install Firebase CLI
      - run:
          name: Install Firebase CLI
          command: |
            mkdir -p ~/.npm-global
            npm install -g firebase-tools --prefix ~/.npm-global
            echo 'export PATH=/project/programming/e-com/Zomato/IRIS-Flower-classification-master/mlops_project/Toyota/toyota_dvc/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

          
      # Log in to Firebase
      - run:
          name: Firebase Login
          command: |
            echo 1//0gwMHq_kd_t7sCgYIARAAGBASNwF-L9Irui-OR9oN-GlgGNgPe1-W5YVjnpvac9zPzlvtSS8sFPKMXHc31qBUgQJFAe0UYUcS6bc | base64 --decode > firebase_token
            #firebase login --token $(cat firebase_token)
            firebase login --token $(cat 1//0gwMHq_kd_t7sCgYIARAAGBASNwF-L9Irui-OR9oN-GlgGNgPe1-W5YVjnpvac9zPzlvtSS8sFPKMXHc31qBUgQJFAe0UYUcS6bc)
      # Deploy to Firebase
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token 1//0gwMHq_kd_t7sCgYIARAAGBASNwF-L9Irui-OR9oN-GlgGNgPe1-W5YVjnpvac9zPzlvtSS8sFPKMXHc31qBUgQJFAe0UYUcS6bc

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
