version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: .
          paths:
            - models
            - test-results

  deploy:
    docker:
      - image: python:3.8

    steps:
      #- run: echo "Deploying to production server"
      #- attach_workspace:
      #    at: /workspace

      # Install Streamlit
      #- run:
      #    name: Install Streamlit
      #    command: |
      #      pip install streamlit

      # Deploy Streamlit app
      #- run:
      #    name: Deploy Streamlit App
      #    command: |
      #      streamlit run app.py &
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl /usr/local/bin/
            
      - run: echo "Deploying to production server"
      - run:
          name: Configure kubectl
          command: |
            echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yaml
            export KUBECONFIG=$PWD/kubeconfig.yaml

      - run:
          name: List files in manifests directory
          command: ls /home/mayank/kubernetes/manifests

      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f /home/mayank/kubernetes/manifests
      

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
