version: 2.1

jobs:
  test:
    docker:
      - image: lambdatest/python:3.8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest

      - store_test_results:
          path: /path/to/test/reports

  deploy:
    docker:
      - image: lambdatest/python:3.8

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:5lFrf/UP0g00QTx7+i7SVeYR5cMlBtfzjCGXoJMWXTY"

      - run:
          name: Deploy to production
          command: |
            ssh user@your-server "cd /path/to/deployment && git pull origin master && ./deploy.sh"

  store-artifacts:
    docker:
      - image: lambdatest/python:3.8

    steps:
      - checkout

      - run:
          name: Store artifacts
          command: |
            mkdir -p ~/artifacts
            cp scatter_plot.html ~/artifacts
            cp pie_plot.html ~/artifacts
            cp bar_plot.html ~/artifacts
            cp line_plot.html ~/artifacts

      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master

      - store-artifacts:
          requires:
            - test
          filters:
            branches:
              only:
                - master
