version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest

      - persist_to_workspace:
          root: /app
          paths:
            - models/
            - scatter_plot.html
            - pie_plot.html
            - bar_plot.html
            - line_plot.html

  deploy:
    docker:
      - image: node:14

    working_directory: /app

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Deploy to Netlify
          command: |
            # Add Netlify deployment steps here
            # For example, use Netlify CLI to deploy your app
            npm install -g netlify-cli
            netlify deploy --prod --auth nfp_fLKeWEoR4JhmGmwWk3SfHvDji4PaHp7t888c

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
