version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      # Save plots as artifacts
      - persist_to_workspace:
          root: .
          paths:
            - scatter_plot.html
            - pie_plot.html
            - bar_plot.html
            - line_plot.html

  deploy:
    docker:
      - image: python:3.8

    steps:
      - attach_workspace:
          at: /workspace

        # Build Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-dockerhub-username/your-image-name:latest .

      # Login to DockerHub
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Push Docker image to DockerHub
      - run:
          name: Push to DockerHub
          command: |
            docker push your-dockerhub-username/streamlit-app:latest
      
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
