version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      # Save plots as artifacts
      - persist_to_workspace:
          root: .
          paths:
            - scatter_plot.html
            - pie_plot.html
            - bar_plot.html
            - line_plot.html

  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - attach_workspace:
          at: /workspace

      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku --version

      # Log in to Heroku
      - run:
          name: Heroku Login
          command: |
            echo 65270893-27cc-471a-9db3-3041dd3fa00a | docker login --username=_ --password-stdin registry.heroku.com
            heroku container:login

      # Push Docker image to Heroku
      - run:
          name: Deploy to Heroku
          command: |
            docker tag your-image registry.heroku.com/your-app/web
            docker push registry.heroku.com/your-app/web
            heroku container:release web -a your-app

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
