version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
 
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      # Save plots as artifacts
      - persist_to_workspace:
          root: .
          paths:
            - scatter_plot.html
            - pie_plot.html
            - bar_plot.html
            - line_plot.html

  deploy:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: False

      - run:
          name: Build docker image 
          command: |
            docker build -t toyotaapp -t mayank035/toyotaapp:latest .
            echo $DOCKERHUB_PASSWORD | docker login -u mayank035 --password-stdin
            docker push mayank035/toyotaapp:latest
            docker pull mayank035/toyotaapp:latest

      - run:
          name: Deploy Docker image to localhost
          command: |
            CONTAINER_ID=$(docker run -d -p 8080:80 mayank035/toyotaapp:latest)
            echo "Container ID: $CONTAINER_ID"
            docker logs $CONTAINER_ID
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          post-steps:
            - store_artifacts:
                path: test-results
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
